name: spacecats-mps
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - pytorch=2.4.1
  - torchvision=0.19.1
  - numpy
  - scipy
  - scikit-learn
  - scikit-image
  - torchmetrics
  - h5py
  - jsonschema
  - pandas
  - pyyaml
  - matplotlib
  - seaborn
